### ISSUE TITLE
How to select Singapore and US datacenter

### ISSUE THREAD

**Issue by simonjackson1982** [kaosf/conoha#1]
Hi, Conoha now has Singapore and US datacenter, how do I specify Singapore or US datacenter in CLI? It looks like it is hard coded to Tokyo datacenter. Thanks.

**Comment by kaosf** [comment]
There is no way to select a region, now. You are right, it is hard coded.

I created a branch for switching regions. https://github.com/kaosf/conoha/pull/2

You will be able to select a region via `~/.conoha-config.json` like following:

``` json
{
  "username": "gncu123456789",
  "password": "your-password",
  "region": "tyo1",
  "tenant_id": "0123456789abcdef",
  "public_key": "your-registered-public-key-name"
}
```

**Comment by kaosf** [comment]
I released version 0.9.0 now.

**Comment by kaosf** [comment]
If you find a new problem or an error, could you tell me it as a new issue? Thanks.

**Comment by simonjackson1982** [comment]
Thank you very much for your quick action, it works great so far, I will definitely feedback if there is any new issue, thanks again for your great work!
