### ISSUE TITLE
How to filter VPS based on server name?

### ISSUE THREAD

**Issue by simonjackson1982** [kaosf/conoha#3]
Hi, 

For example, I have 5 servers:

AAA1
AAA2
AAA3
BBB1
BBB2

How to I filter servers start with "AAA"? Thank you!

**Comment by kaosf** [comment]
There is no way to filter servers. This gem provides the command "conoha" (and "conoharant" but this command is not related to this issue) that can manage one server via UUID.

You have to run 3 commands to manipulate 3 servers, for example:

``` sh
conoha boot UUID1
conoha boot UUID2
conoha boot UUID3
```

**Comment by kaosf** [comment]
You can check UUIDs with `conoha vpslist` command or on the web control panel.

![conoha control panel 2016-07-26 15-28-49](https://cloud.githubusercontent.com/assets/1495128/17128204/fa4cf736-5345-11e6-9a5c-cc7eb73695e8.png)

**Comment by kaosf** [comment]
This gem doesn't have the features based on "Name Tag". Sorry X-(

**Comment by kaosf** [comment]
This gem is not the orchestration tool, now. It's only a wrapper of the complex `curl` commands on ConoHa API documentation's examples.

**Comment by simonjackson1982** [comment]
Thanks, can we get VPS name tag based on UUID as workaround?

**Comment by kaosf** [comment]
Hmmm... some APIs related to the "name tag" are here:
- https://www.conoha.jp/docs/compute-get_server_metadata.html
- https://www.conoha.jp/docs/compute-update_metadata.html

So, I try to create a new command like `conoha nametag UUID`.

**Comment by kaosf** [comment]
OK! I got the nametag sub command implementation!

Just a moment. I'll release 0.9.2.

**Comment by simonjackson1982** [comment]
Thank you! The reason I am asking for this is because I need to manage around 100+ servers and they have different name tags so I know what they are for, I need to manage them using name tags otherwise it will be confusing.

**Comment by kaosf** [comment]
OK, I think you need to the nametag-UUID dictionary. How about is the following idea?

``` sh
conoha vpslist | ruby -e 'eval(STDIN.read).each{|e|puts e}' > uuidlist.txt
cat uuidlist.txt | xargs -I {} conoha nametag {} > nametaglist.txt
paste -d"\n" nametaglist.txt uuidlist.txt > dictionary.txt
```

You will get `dictionary.txt` e.g.

```
name1
uuid1
name2
uuid2
name3
uuid3
```

Next, prepare the Ruby script `myconoha.rb` like following:

``` ruby
#!/usr/bin/env ruby

a = File.read('dictionary.txt').split("\n")
h = Hash[*a]
first = ARGV[1]
uuid = h[ARGV.shift]
ARGV.shift
system("conoha #{first} #{uuid} #{ARGV.join(' ')}")
```

Next, add an executable flag to the file:

``` sh
chmod +x myconoha.rb
```

Then, you can run any `conoha` command via your name tags like following:

``` sh
./myconoha.rb name1 boot
# equals to `conoha uuid1 boot`

./myconoha.rb name2 shutdown
# equals to `conoha uuid2 shutdown`
```

**Comment by simonjackson1982** [comment]
Thank you so much, let me test to see how it goes!

**Comment by kaosf** [comment]
If you have any question about my solutions, I want to support you as well as possible.

**Comment by simonjackson1982** [comment]
for example the content of dictionary.txt will be like following

```
ss001
uuid-1
ss002
uuid-2
xx003
uuid-3
xx004
uuid-4

```

Can we update myconoha.rb so when I type:

`./myconoha.rb ss
`

it will automatically return following?

```
uuid-1
uuid-2
```

Thank you so much!

**Comment by kaosf** [comment]
It's easy. Modify `myconoha.rb` to below:

``` ruby
#!/usr/bin/env ruby

a = File.read('dictionary.txt').split("\n")
h = Hash[*a]
keyword = ARGV.first
keys = h.keys.select { |e| e.include? keyword }
keys.each { |e| puts h[e] }
```

And then, run it.

``` sh
./myconoha.rb ss
```

You'll get

```
uuid-1
uuid-2
```

**Comment by kaosf** [comment]
I close this issue. This gem will not have a feature for orchestration. Thanks.

**Comment by simonjackson1982** [comment]
Understood, thank you so much!
