### ISSUE TITLE
Can we create VPS using custom name tag? 

### ISSUE THREAD

**Issue by simonjackson1982** [kaosf/conoha#5]
For example, can I create VPS called test001? Many thanks.

**Comment by kaosf** [comment]
I have modified `Conoha.create` method to enable to pass a name tag and release version 0.9.3. You can specify name tag via 4th argument.

``` sh
conoha create ubuntu g-1gb nametagasyoulike
```

**Comment by simonjackson1982** [comment]
Thank you so much for your quick action! I will test and provide feedback!

**Comment by simonjackson1982** [comment]
I tried to run:

`/usr/local/bin/conoha create ubuntu g-1gb ss001`

But return error:

`undefined method [] for nil:NilClass`

Can you please help to check?

**Comment by simonjackson1982** [comment]
I am already on 0.9.3

**Comment by kaosf** [comment]
I can't reproduce the same bug. In my case

``` sh
conoha create ubuntu g-1gb mynametag
#=> "uuid"
```

It succeeded. ????

**Comment by simonjackson1982** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/20623101/17178138/d0b1981c-5446-11e6-9282-44d9d529d280.JPG)

This is strange, where should I look at please?

**Comment by kaosf** [comment]
`conoha create ...` command goes through `exe/conoha` line 74

``` ruby
    pp Conoha.create *ARGV
```

and next `lib/conoha.rb` line 100 method

``` ruby
  def self.create(os, ram, name_tag = nil)
    image_ref = image_ref_from_image_tag(image_tag_dictionary(os))
    uri = "https://compute.#{region}.conoha.io/v2/#{tenant_id}/servers"
    payload = {
      server: {
        adminPass: randstr,
        imageRef: image_ref,
        flavorRef: flavor_ref(ram),
        key_name: public_key,
        security_groups: [{name: 'default'}, {name: 'gncs-ipv4-all'}],
      }
    }
    if name_tag
      payload[:server].merge!({metadata: {instance_name_tag: name_tag}})
    end
    res = https_post uri, payload, authtoken
    JSON.parse(res.body)["server"]["id"]
  end
```

... so, the error of `undefined method '[]' for nil:NilClass` can occur in the step of:

``` ruby
    JSON.parse(res.body)["server"]["id"]
```

`JSON.parse(res.body)` is evaluated to `nil`.

So, could you try to insert `puts` for debugging like following:

``` ruby
  def self.create(os, ram, name_tag = nil)
    image_ref = image_ref_from_image_tag(image_tag_dictionary(os))
    uri = "https://compute.#{region}.conoha.io/v2/#{tenant_id}/servers"
    payload = {
      server: {
        adminPass: randstr,
        imageRef: image_ref,
        flavorRef: flavor_ref(ram),
        key_name: public_key,
        security_groups: [{name: 'default'}, {name: 'gncs-ipv4-all'}],
      }
    }
    if name_tag
      payload[:server].merge!({metadata: {instance_name_tag: name_tag}})
    end
    res = https_post uri, payload, authtoken
    # Debugging code start
    puts '------------------------------'
    puts res.code
    puts res.body
    puts '------------------------------'
    # Debugging code finish
    JSON.parse(res.body)["server"]["id"]
  end
```

and let me to know the outputs.

**Comment by simonjackson1982** [comment]
Thank you very much for your quick response as always, let me try and get back to you.

**Comment by simonjackson1982** [comment]
Error message is "Invalid key_name provided." 

Issue resolved after I update with correct public key name, thanks a lot for your help!
