### ISSUE TITLE
How to make the script working for Z.com

### ISSUE THREAD

**Issue by simonjackson1982** [kaosf/conoha#6]
Hi,

Z.com is also created by GMO and I noticed they are actually using exactly the same system and API. I tried to update the entry point so it can point to Z.com and I can authenticate successfully!

But I can't create new VPS using your script, hitting error:

{"message":"Invalid flavorRef provided","code":400}}

I think with a little customization your program can also support Z.com, will you add this feature please?

**Comment by kaosf** [comment]
Hello,

The flavor_ref dictionary is hard coded now. ref. https://github.com/kaosf/conoha/blob/78e3e84adc38c7f5bfc1ea4306d2ba2e3c74baae/lib/conoha.rb#L295-L303

You may modify that code. But, before doing that, detect flavor UUIDs.

You have an authentication token after running `conoha authenticate`. It is a value of the key of `"authtoken"` in `~/.conoha-config.json`.

Run the following command with the `authtoken` and `tenant_id`. e.g.:

``` sh
curl -i -X GET \
-H "Accept: application/json" \
-H "X-Auth-Token: YOUR_AUTH_TOKEN" \
https://Z.com/v2/TENANT_ID/flavors/detail
```

ref. https://www.conoha.jp/docs/compute-get_flavors_detail.html

Modify `Z.com` to the correct hostname which you used :-)

**Comment by simonjackson1982** [comment]
Got it, thank you so much!

**Comment by simonjackson1982** [comment]
It worked, thanks~!
